# Generated by Django 4.2.16 on 2024-10-09 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_options_booking_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='table',
        ),
    ]
