# Generated by Django 4.2.16 on 2024-10-10 20:11

from django.db import migrations

def create_customer_profiles(apps, schema_editor):
    # Get the User and Customer models
    User = apps.get_model('auth', 'User')
    Customer = apps.get_model('booking', 'Customer')
    
    # Iterate through users who don't have a customer profile and create one
    for user in User.objects.filter(customer__isnull=True):
        Customer.objects.create(user=user, phone_number='')  # Add default phone number if necessary


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_booking_table'),
    ]

    operations = [
    ]
