# Generated by Django 4.2.16 on 2024-10-13 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20241010_2011'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table',
        ),
    ]
